# Generated by Django 2.2.9 on 2020-01-07 08:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_set_ondelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='contacts+', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='contactgroups+', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
